leftnav:
- identifier: 84f14429-5355-41a8-955e-97a046c0581a
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: e89e2633-dec3-43d5-9a9f-460ba9bf2381
  name: Calendar
  url: /pages/readings
  weight: 20
- identifier: 169c70da-ef12-479c-a679-d3edd879838c
  name: Readings
  url: /pages/readings-v2
  weight: 30
- identifier: b0c6d06d-639c-43cb-98b0-ad3da2d9e948
  name: Essays
  url: /pages/essays
  weight: 40
- identifier: f6c5638e-e9c8-49f0-87d4-bfed19acd4f7
  name: Paper 1
  parent: b0c6d06d-639c-43cb-98b0-ad3da2d9e948
  url: /pages/essay-1
  weight: 10
- identifier: 81e7bf05-e342-4599-b2a8-44f76fba2c43
  name: Paper 2
  parent: b0c6d06d-639c-43cb-98b0-ad3da2d9e948
  url: /pages/essay-2
  weight: 20
- identifier: cbe8b9d8-448e-457e-90dc-c6e71fd7c858
  name: Paper 2 Revision
  parent: b0c6d06d-639c-43cb-98b0-ad3da2d9e948
  url: /pages/essay-2-revision
  weight: 30
- identifier: 6cddd6a0-111c-4b7d-8743-10397ab6b795
  name: Paper 3
  parent: b0c6d06d-639c-43cb-98b0-ad3da2d9e948
  url: /pages/essay-3
  weight: 40
